trustPolicyExclude:
  - 'detect-port@1.6.1'
  - 'chokidar@4.0.3'

packages:
  - 'apps/*'
  - 'libs/*'
  - 'tools/*'

onlyBuiltDependencies:
  - '@alicloud/openapi-core'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - esbuild
  - git-commit-msg-linter
  - msgpackr-extract
  - nx
  - protobufjs
  - sharp
  - simple-git-hooks
  - unrs-resolver

peerDependencyRules:
  ignoreMissing:
    - axios

allowBuilds:
  '@alicloud/openapi-core': set this to true or false
  '@nestjs/core': set this to true or false
  '@scarf/scarf': set this to true or false
  esbuild: true
  git-commit-msg-linter: set this to true or false
  msgpackr-extract: true
  nx: true
  protobufjs: true
  sharp: true
  simple-git-hooks: set this to true or false
  unrs-resolver: set this to true or false
